# Docker Compose file for School Tutor Agent with Weaviate
version: '3.8'

services:
  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.20.5
    ports:
      - "9090:8080"
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - tutor-network

  # Text-to-vector transformer module for Weaviate
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    environment:
      ENABLE_CUDA: "0"  # Set to 1 if you have a CUDA-enabled GPU
    networks:
      - tutor-network

  # Streamlit application
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080  # This is the internal port within the Docker network
      - PYTHONPATH=/app
      # Add other environment variables from .env file if needed
    volumes:
      - .:/app
    depends_on:
      - weaviate
    networks:
      - tutor-network

networks:
  tutor-network:
    driver: bridge

volumes:
  weaviate_data:
    driver: local
